In [1]:
print(0b10)

2


In [2]:
type(10)

int

In [3]:
type('abc')

str

In [4]:
a=11
print(type(a))

<class 'int'>


In [5]:
a='string'
print(type(a))

<class 'str'>


In [6]:
y=2.8
print(type(y))

<class 'float'>


In [7]:
type(.4)

float

In [8]:
x=35e3
print(type(x))

<class 'float'>


In [9]:
type(True)

bool

In [10]:
print("college")

college


In [11]:
type("college")

str

In [12]:
print("college(')")

college(')


In [13]:
print("college('/)")

college('/)


In [1]:
#1D array of some prime numbers
import numpy as np
prime_array=np.array([1,3,5,7,11])
print(prime_array)

[ 1  3  5  7 11]


In [2]:
type(prime_array[-1])

numpy.int32

In [5]:
#2D array
sample_array =np.array([[1,2],[3,4]])
print(sample_array)

[[1 2]
 [3 4]]


In [6]:
#3D array
sample_array1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(sample_array1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
#Array attributes
#ndarray.shape
sample_array2=np.array([[1,2,3],[4,5,6]])
print(sample_array2.shape)

(2, 3)


In [14]:
#ndarray.ndim
array_of_integer=np.array([0,1,2,3,4,5,6,7,8,9])
print("dimension of array_of_interger=",array_of_integer.ndim)

dimension of array_of_interger= 1


In [15]:

sample_array3=np.array([[1,2,3],[4,5,6]])
print("dimension of sample_array3=",sample_array3.ndim)

dimension of sample_array3= 2


In [22]:
#ndarray.size
array_of_integer=np.array([0,1,2,3,4,5,6,7,8,9])
print("The total number of elements in our array array_of_integer=",{array_of_integer.size})

The total number of elements in our array array_of_integer= {10}


In [23]:
sample_2d_array=np.array([[1,2,3],[4,5,6]])
print(f"the total number of elements in our array sample_2d_array=",{array_of_integer.size})

the total number of elements in our array sample_2d_array= {10}


In [24]:
#ndarray.dtype
my_array=np.array([1,2,3,4,5])
print(my_array.dtype)

int32


In [25]:
my_list=[1,2,3,4,5,'abc']
print(my_list)

[1, 2, 3, 4, 5, 'abc']


In [26]:
#ndarray.astype
arrow=np.array([2,3,4])
print(arrow.dtype)

int32


In [27]:
#change the datatype to float
arrow=arrow.astype('float64')
print(arrow)
print(arrow.dtype)

[2. 3. 4.]
float64
